-- =====================================================================
--  RS or Single — Supabase Backend
--  Supabase Dashboard > SQL Editor ထဲ ဒီ SQL အကုန် ကူးထည့်ပြီး RUN နှိပ်ပါ။
-- =====================================================================

-- ၁. data သိမ်းမယ့် table
create table if not exists public.predictions (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now(),
  name        text,
  dob         text,
  food        text,
  result      text,   -- "RS" or "Single"
  score       int     -- ချစ်ခြင်းစွမ်းအင် %
);

-- ၂. Row Level Security ဖွင့် (default အရ ဘာမှ ဖတ်/ရေး မရတော့)
alter table public.predictions enable row level security;

-- ၃. သူငယ်ချင်းတွေ (anon) ⟶ INSERT ပဲ ခွင့်ပြု (ဖြေတာ သိမ်းနိုင်ဖို့)
create policy "anyone can insert"
  on public.predictions
  for insert
  to anon
  with check (true);

-- 🔒 မှတ်ချက်: SELECT policy မထည့်ထားလို့ anon က data ဖတ်လို့ မရဘူး။
--    ဒါကြောင့် သူငယ်ချင်းတွေ အချင်းချင်း data မမြင်ရဘူး။
--    သင် (owner) ကတော့ Dashboard > Table Editor မှာ login လုပ်ပြီး အကုန် ကြည့်ရတယ်။

